#!/bin/sh
echo "🚀 Running Lint Staged 🚀"
echo "|=========================|"
echo "|=========================|"

npx lint-staged

if [ $? -eq 0 ]; then
  echo "✅ Lint passed! ✅"
else
  echo "❌ Lint failed! ❌"
  exit 1
fi
